name: Desktop
on:
  push:
    paths:
      - 'desktop/**'
  pull_request:
    paths:
      - 'desktop/**'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        # install dependencies here
    - name: Run tests
      run: |
        # run tests here
    - name: Build
      run: |
        # build the desktop here
